import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Heart, HandHelping, Cross, Shield, UserCheck, MapPin, ChevronDown } from 'lucide-react';
import Layout from '../components/layout/Layout';
import ScrollReveal from '../components/ui/ScrollReveal';

// Timeline Data
const timelineItems = [
    { date: "Mid-2015", title: "The Vision Begins", description: "While on a school-related visit to Sakote, Nhyira felt a strong burden to begin a music ministry, pondering it prayerfully.", side: "left" },
    { date: "November 2015", title: "Yielding to the Call", description: "After much deliberation and a growing burden, Nhyira yielded to the call to establish the ministry.", side: "right" },
    { date: "November 22, 2015", title: "First Official Meeting", description: "The inaugural meeting of Worshipper's Praise Incorporated was held in Lecture Room 5 of the University for Development Studies' Library block with eleven pioneers. The vision and mission were explained, and prayers were offered.", side: "left" },
];

// Core Values
const coreValues = [
    { icon: Heart, title: "Holiness & Right Living" },
    { icon: HandHelping, title: "Willingness & Commitment" },
    { icon: Cross, title: "Discipline & Diligence" },
    { icon: Shield, title: "Integrity" },
    { icon: UserCheck, title: "Responsibility" },
];

// Aims and Objectives
const aims = [
    "To train Christian musicians in the praise and worship ministry",
    "To lead congregations of believers to offer worship and praise to God in spirit, in truth, and the beauty of holiness",
    "To deepen and strengthen personal faith in Christ Jesus and the spiritual life of members through the study of the Bible, prayer, and fellowship",
    "To inculcate into the membership, a lifestyle of modesty and decency",
    "To carry out evangelism at various locations across the country",
    "To help members to identify and develop their ministries and leadership potentials",
];

// Chapters Data
const chapters = [
    { city: "Tamale", description: "We have a vibrant group of ministers in Tamale championing the course of the ministry. This includes various professionals and students. Being the first Chapter of WPI, it produced the earliest members of the ministry and currently has the largest numbers.", email: "tamale@wpighana.com" },
    { city: "Wa", description: "Having started in 2020, the Wa Chapter has grown to become a notable ministry in the town. Just like in Tamale, it comprises members from various professions who will stop at nothing to ensure that they excel in the work of God while excelling in their professional fields.", email: "wa@wpighana.com" },
    { city: "Accra", description: "The Accra chapter is the youngest of the ministry. As it is located in arguably the busiest city in the country, the members are aware of the magnitude of the task to lift Christ high, amidst the hustle and bustle that so easily captures the hearts and minds of people, including those who call upon the name of the Lord.", email: "accra@wpighana.com" },
];

// Basis of Faith
const basisOfFaith = [
    { title: "1. The Bible", content: "We believe that the Bible is the foundational guide for Christian living; it is as light shining in darkness; it is the surest word of prophecy. We believe that all scripture is giving by the inspiration of God and is profitable for doctrine, reproof, correction, and instruction in righteousness, for the purpose of perfecting God's people and equipping them with the necessary resources for purposeful and godly living. We also believe that God's word is eternal and unchanging. (II Timothy 3:16-17, II Peter1:19-21, Isaiah 40:8)" },
    { title: "2. The One True God", content: "We believe in the one true triune God (One God, in three persons – Father, Son, and Spirit). (Psalm 90:2, Isaiah 46:9, Deuteronomy 6:4, Matthew 28:19)" },
    { title: "3. Man's depraved nature", content: "We believe that all men are born sinners and have fallen short of the glory of God. Men are, by nature, children of wrath and without God until they are saved by Jesus Christ. (Romans 3:23, Ephesians 2:1-3, 12)" },
    { title: "4. The Savior", content: "We believe that Jesus, the Son of God, was born in the flesh to save all mankind through his death, burial, and resurrection, and without Him, no one has access to the Father. (John 3:16, John14:6, Isaiah 9:6)" },
    { title: "5. Repentance, regeneration, justification and sanctification", content: "We believe that all men need to repent from their sins, and all believer need to repent from dead works. We also believe that we are regenerated by the Holy Spirit. We are also sanctified and justified by God. (Hebrews 6:1, Romans 8:30, Titus 3:5, Ephesians 5:26)" },
    { title: "6. Baptism, gifts and fruit of the Holy Spirit", content: "We believe in the baptism of the Holy Ghost, His diverse gifts which are given for the profit of all, and the fruit of the Spirit, against which there is no law. (Acts 1:8, Galatians 5:22, I Corinthians 12:4-11)" },
    { title: "7. Divine healing", content: "We believe that Jesus Christ is our healer and has empowered us to heal the sick in His name, and that the prayer of faith saves the sick. (James 5:15-16, Matthew 15:30, Acts 3:1-8)" },
    { title: "8. Tithes and Offering", content: "We believe in the principle of giving according to scripture in freewill offerings and in tithing by faith, but not by law. (Malachi 3:10, Luke 6:38, Acts 4:34-35)" },
    { title: "9. The grace of God", content: "We believe in the grace of God as a necessary condition for salvation and for living a glorious Christian life. We also believe that the grace of God teaches us to deny ungodliness and the world, and to live as God will have us do, in this world. (Ephesians 2:8, Titus 2:11-12, Romans 6:14)" },
    { title: "10. The second coming and the next life", content: "We believe in the return of our Lord Jesus Christ. He will return with his reward to give to everyone according to their works. We also believe in life after this world. (I Thessalonians 4:16-17, Revelations 22:12, Revelations 20:4)" },
];

// Accordion Item Component
const AccordionItem = ({ item, isOpen, onClick }) => (
    <div className="border-b border-gray-200">
        <button onClick={onClick} className="w-full py-4 px-6 flex justify-between items-center text-left hover:bg-gray-50 transition-colors">
            <span className="font-semibold text-primary">{item.title}</span>
            <ChevronDown className={`w-5 h-5 text-primary transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} />
        </button>
        <div className={`overflow-hidden transition-all duration-300 ${isOpen ? 'max-h-96 pb-4' : 'max-h-0'}`}>
            <p className="px-6 text-gray-600 leading-relaxed">{item.content}</p>
        </div>
    </div>
);

const AboutPage = () => {
    const [openAccordion, setOpenAccordion] = useState(null);

    return (
        <Layout>
            {/* Hero */}
            <section className="relative h-[60vh] min-h-[400px] flex items-center justify-center text-center text-white overflow-hidden">
                <div className="absolute inset-0 z-0">
                    <img src="/Assets/Pictures/About Us (2).jpg" alt="About Us" className="w-full h-full object-cover" />
                    <div className="absolute inset-0 bg-black/50" />
                </div>
                <div className="relative z-10 container mx-auto px-4">
                    <h1 className="text-4xl md:text-6xl font-bold mb-4 drop-shadow-lg">About Us</h1>
                    <p className="text-lg md:text-xl opacity-90 drop-shadow-md">Learn more about our story, mission, and what we believe.</p>
                </div>
            </section>

            {/* Our Story (Horizontal Timeline) */}
            <section className="py-24 bg-white overflow-hidden">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary text-center mb-24">Our Story</h2>
                        <div className="relative min-h-[600px] flex items-center">
                            {/* Central Horizontal Line (Desktop) */}
                            <div className="absolute top-1/2 left-0 w-full h-0.5 border-t-2 border-dashed border-primary/30 -translate-y-1/2 hidden md:block" />

                            <div className="flex md:flex-row flex-col gap-12 md:gap-0 w-full md:justify-between items-center relative z-10">
                                {timelineItems.map((item, i) => (
                                    <div key={i} className="flex-shrink-0 w-full md:w-1/3 px-6 relative flex flex-col items-center">

                                        {/* Vertical Connector Stem (Desktop) */}
                                        <div className={`hidden md:block absolute w-0.5 h-24 bg-primary/20 
                                            ${i % 2 === 0 ? 'bottom-1/2' : 'top-1/2'}`} />

                                        {/* Timeline Marker (Dot) */}
                                        <div className="hidden md:flex absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-20">
                                            <div className="w-6 h-6 bg-white rounded-full border-4 border-primary shadow-xl flex items-center justify-center">
                                                <div className="w-2 h-2 bg-primary rounded-full" />
                                            </div>
                                        </div>

                                        {/* Content Card */}
                                        <div className={`bg-white rounded-2xl shadow-xl p-8 border-t-8 border-primary transition-all duration-500 hover:shadow-2xl hover:-translate-y-3 w-full max-w-sm relative z-10
                                            ${i % 2 === 0 ? 'md:mb-64' : 'md:mt-64'}`}>
                                            <div className="absolute -top-4 left-6 bg-tertiary text-white text-xs font-bold px-3 py-1 rounded-full shadow-md">
                                                {item.date}
                                            </div>
                                            <h3 className="text-xl font-bold text-primary mt-2">{item.title}</h3>
                                            <p className="text-gray-600 mt-4 text-sm leading-relaxed">{item.description}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </ScrollReveal>
                </div>
            </section>

            {/* Mission & Vision */}
            <section className="py-20 bg-gray-50">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <div className="grid md:grid-cols-2 gap-8">
                            <div className="bg-white rounded-xl shadow-lg p-8 border-t-4 border-primary">
                                <h3 className="text-2xl font-bold text-primary mb-4">Our Vision</h3>
                                <p className="text-gray-600 leading-relaxed">A worldwide ministry that turns the hearts of a myriad of people towards Jesus Christ and emphasizes daily communion with His Spirit.</p>
                            </div>
                            <div className="bg-white rounded-xl shadow-lg p-8 border-t-4 border-secondary">
                                <h3 className="text-2xl font-bold text-secondary mb-4">Our Mission</h3>
                                <p className="text-gray-600 leading-relaxed">To train Christian musicians and reach out to souls through music.</p>
                            </div>
                        </div>
                    </ScrollReveal>
                </div>
            </section>

            {/* Core Values */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary text-center mb-12">Our Core Values</h2>
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6">
                            {coreValues.map((value, i) => (
                                <div key={i} className="flex flex-col items-center text-center p-6 bg-gray-50 rounded-xl hover:shadow-lg transition-shadow">
                                    <value.icon className="w-12 h-12 text-primary mb-4" />
                                    <h4 className="font-semibold text-gray-800">{value.title}</h4>
                                </div>
                            ))}
                        </div>
                    </ScrollReveal>
                </div>
            </section>

            {/* Aims and Objectives */}
            <section className="py-20 bg-gray-50">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary text-center mb-12">Aims and Objectives</h2>
                        <ul className="max-w-3xl mx-auto space-y-4">
                            {aims.map((aim, i) => (
                                <li key={i} className="flex items-start gap-3">
                                    <span className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0" />
                                    <span className="text-gray-600">{aim}</span>
                                </li>
                            ))}
                        </ul>
                    </ScrollReveal>
                </div>
            </section>

            {/* Membership */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4 text-center">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary mb-6">Membership</h2>
                        <p className="max-w-3xl mx-auto text-gray-600 leading-relaxed">
                            Our membership is open to all interested Christians who are prepared to be committed to the vision, mission, aims, objectives, and values of the ministry, all of which are based on the principles set out in the Bible. All members must sign a commitment and membership form to signify their agreement with the group's principles and membership.
                        </p>
                    </ScrollReveal>
                </div>
            </section>

            {/* Chapters */}
            <section className="py-20 bg-gray-50">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary text-center mb-12">Our Chapters</h2>
                        <div className="grid md:grid-cols-3 gap-8">
                            {chapters.map((chapter, i) => (
                                <div key={i} className="bg-white rounded-xl shadow-lg p-8 text-center hover:shadow-xl transition-shadow">
                                    <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6">
                                        <MapPin className="w-8 h-8 text-primary" />
                                    </div>
                                    <h3 className="text-2xl font-bold text-primary mb-4">{chapter.city}</h3>
                                    <p className="text-gray-600 text-sm mb-4">{chapter.description}</p>
                                    <p className="text-sm"><strong>Contact:</strong> {chapter.email}</p>
                                </div>
                            ))}
                        </div>
                    </ScrollReveal>
                </div>
            </section>

            {/* Start a Chapter */}
            <section className="py-20 bg-primary text-white text-center">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold mb-6">Start a Chapter</h2>
                        <p className="max-w-2xl mx-auto opacity-90 mb-8">Don't see a chapter in your area? We're always looking to expand our ministry. If you're interested in starting a new chapter, please contact us for more information.</p>
                        <Link to="/contact" className="inline-block px-8 py-3 bg-white text-primary font-bold rounded-full hover:bg-gray-100 transition-colors shadow-lg">Contact Us</Link>
                    </ScrollReveal>
                </div>
            </section>

            {/* Basis of Faith */}
            <section className="py-20 bg-gray-50">
                <div className="container mx-auto px-4">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary text-center mb-12">Basis of Faith</h2>
                        <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-lg overflow-hidden">
                            {basisOfFaith.map((item, i) => (
                                <AccordionItem
                                    key={i}
                                    item={item}
                                    isOpen={openAccordion === i}
                                    onClick={() => setOpenAccordion(openAccordion === i ? null : i)}
                                />
                            ))}
                        </div>
                    </ScrollReveal>
                </div>
            </section>

            {/* Get Involved */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4 text-center">
                    <ScrollReveal>
                        <h2 className="text-3xl md:text-4xl font-bold text-primary mb-6">Get Involved</h2>
                        <p className="max-w-2xl mx-auto text-gray-600 mb-8">We're always looking for passionate individuals to join our ministry. Whether you're a musician, a vocalist, or simply have a heart for worship, there's a place for you at Worshipper's Praise Incorporated.</p>
                        <div className="flex flex-wrap justify-center gap-4">
                            <Link to="/contact" className="px-6 py-3 bg-primary text-white font-bold rounded-full hover:bg-primary/90 transition-colors">Contact Us</Link>
                            <Link to="/events" className="px-6 py-3 bg-primary/10 text-primary font-semibold rounded-full hover:bg-primary/20 transition-colors">Our Events</Link>
                            <Link to="/music" className="px-6 py-3 bg-primary/10 text-primary font-semibold rounded-full hover:bg-primary/20 transition-colors">Our Music</Link>
                        </div>
                    </ScrollReveal>
                </div>
            </section>
        </Layout>
    );
};

export default AboutPage;
